
apiVersion: v1
kind: Secret
metadata:
  name: backends-secret
type: Opaque
stringData:
  # PostgreSQL connection strings
  CatalogDb: "Host=${PG_FQDN};Port=5432;Database=eshop;Username=${PG_USER};Password=${PG_PASS};Ssl Mode=Require;Trust Server Certificate=True;"
  OrderingDb: "Host=${PG_FQDN};Port=5432;Database=eshop;Username=${PG_USER};Password=${PG_PASS};Ssl Mode=Require;Trust Server Certificate=True;"

  # Redis
  RedisEndpoint: "${REDIS_HOST}:6379"
  RedisPassword: "${REDIS_KEY}"

  # Messaging (Service Bus)
  ServiceBus: "${SB_CONN}"


 
 # دریافت kubeconfig (همان کلاستر eshop-aks)
# az aks get-credentials -g eshop-rg -n eshop-aks --overwrite-existing

# # ساخت Secret
# kubectl apply -f deploy/k8s/secrets-backends.yaml
# kubectl get secret backends-secret

