apiVersion: v1
kind: Secret
metadata:
  name: backends-secret
type: Opaque
stringData:
  # --- PostgreSQL (Catalog + Ordering) ---
   CatalogDb: "Host=eshop-pg-flex.postgres.database.azure.com;Port=5432;Database=eshop;Username=pgadmin;Password=P@ssw0rd!;Ssl Mode=Require;Trust Server Certificate=True;"
  OrderingDb: "Host=eshop-pg-flex.postgres.database.azure.com;Port=5432;Database=eshop;Username=pgadmin;Password=P@ssw0rd!;Ssl Mode=Require;Trust Server Certificate=True;"

  # --- Azure Redis 
  RedisEndpoint: "eshop-redis-cache.redis.cache.windows.net:6380,ssl=true,password=Oitj8gjM8ZsH9Bkf0gbbIWkr3BKenSVxdAzCaH5YBJU="

  # --- Azure Service Bus 
  ServiceBus: "Endpoint=sb://eshop-sb-ns.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=5B9J7Y/Uy3zyATw2IEn+l0afhfa5ntI4j+ASbJF/9iA="


# az aks get-credentials -g eshop-rg -n eshop-aks --overwrite-existing
# kubectl apply -f deploy/k8s/secrets-backends.yaml
# kubectl get secret backends-secret

