apiVersion: v1
kind: Service
metadata:
  name: basket-api
  labels: { app: basket-api }
spec:
  selector: { app: basket-api }
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
