apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  labels: { app: catalog-api }
spec:
  replicas: 1
  selector:
    matchLabels: { app: catalog-api }
  template:
    metadata:
      labels: { app: catalog-api }
    spec:
      containers:
        - name: catalog-api
          image: eshopacr123.azurecr.io/eshop-catalog:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            # .NET maps "__" to sections => ConnectionStrings:CatalogDb
            - name: ConnectionStrings__CatalogDb
              valueFrom:
                secretKeyRef:
                  name: backends-secret
                  key: CatalogDb
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 20
            periodSeconds: 20

