apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  labels: { app: catalog-api }
spec:
  selector: { app: catalog-api }
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
